#!/usr/bin/env python3
# Grabs the latest TWIL post and return its path relative to _posts/.
#
# There are two notable use cases for this utility:
# 1. Quickly identifying the last post (to know what the next post should be)
# 2. Easily editing the last post e.g. `vim $(./latest)`
import os
import re

if __name__ == '__main__':
    name = ''
    latest = 0

    for file in os.listdir('./_posts'):
        post = re.match(r'[0-9]{4}-[0-9]{2}-[0-9]{2}-TIL-([0-9]+)\.md', file)

        if post and int(post.groups()[0]) > latest:
            name, latest = file, int(post.groups()[0])

    print(f'./_posts/{name}')


