#!/usr/bin/env python3
import os
import re

if __name__ == '__main__':
    name = ''
    latest = 0

    for file in os.listdir('./_posts'):
        post = re.match(r'[0-9]{4}-[0-9]{2}-[0-9]{2}-TIL-([0-9]+)\.md', file)

        if post and int(post.groups()[0]) > latest:
            name = file
            latest = int(post.groups()[0])

    print(name)


