#!/usr/bin/env python3
# Creates a new post with a post number of argv[1]
import datetime
import sys

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f'{sys.argv[0]}: usage: {sys.argv[0]} <post #>', file=sys.stderr)
        sys.exit(1)

    iso = datetime.datetime.now().isoformat()[0:10]
    post = sys.argv[1]
    base = f'{iso}-TIL-{post}'

    with open(f'_posts/{base}.md', 'w') as f:
        f.write('---\n')
        f.write('layout: post\n')
        f.write(f'title: This week I learned {post}\n')
        f.write('categories: [TIL]\n')
        f.write('---\n')
        print(f.name)
